/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as TelemedicinaEmpresarialRouteImport } from './routes/telemedicina-empresarial'
import { Route as StartRouteImport } from './routes/start'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ManualMarcaRouteImport } from './routes/manual-marca'
import { Route as IndividualFamiliarRouteImport } from './routes/individual-familiar'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as IndexRouteImport } from './routes/index'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemedicinaEmpresarialRoute = TelemedicinaEmpresarialRouteImport.update({
  id: '/telemedicina-empresarial',
  path: '/telemedicina-empresarial',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualMarcaRoute = ManualMarcaRouteImport.update({
  id: '/manual-marca',
  path: '/manual-marca',
  getParentRoute: () => rootRouteImport,
} as any)
const IndividualFamiliarRoute = IndividualFamiliarRouteImport.update({
  id: '/individual-familiar',
  path: '/individual-familiar',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/individual-familiar': typeof IndividualFamiliarRoute
  '/manual-marca': typeof ManualMarcaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/start': typeof StartRoute
  '/telemedicina-empresarial': typeof TelemedicinaEmpresarialRoute
  '/termos': typeof TermosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/individual-familiar': typeof IndividualFamiliarRoute
  '/manual-marca': typeof ManualMarcaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/start': typeof StartRoute
  '/telemedicina-empresarial': typeof TelemedicinaEmpresarialRoute
  '/termos': typeof TermosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/individual-familiar': typeof IndividualFamiliarRoute
  '/manual-marca': typeof ManualMarcaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/start': typeof StartRoute
  '/telemedicina-empresarial': typeof TelemedicinaEmpresarialRoute
  '/termos': typeof TermosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design-system'
    | '/individual-familiar'
    | '/manual-marca'
    | '/privacidade'
    | '/start'
    | '/telemedicina-empresarial'
    | '/termos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design-system'
    | '/individual-familiar'
    | '/manual-marca'
    | '/privacidade'
    | '/start'
    | '/telemedicina-empresarial'
    | '/termos'
  id:
    | '__root__'
    | '/'
    | '/design-system'
    | '/individual-familiar'
    | '/manual-marca'
    | '/privacidade'
    | '/start'
    | '/telemedicina-empresarial'
    | '/termos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignSystemRoute: typeof DesignSystemRoute
  IndividualFamiliarRoute: typeof IndividualFamiliarRoute
  ManualMarcaRoute: typeof ManualMarcaRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  StartRoute: typeof StartRoute
  TelemedicinaEmpresarialRoute: typeof TelemedicinaEmpresarialRoute
  TermosRoute: typeof TermosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemedicina-empresarial': {
      id: '/telemedicina-empresarial'
      path: '/telemedicina-empresarial'
      fullPath: '/telemedicina-empresarial'
      preLoaderRoute: typeof TelemedicinaEmpresarialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual-marca': {
      id: '/manual-marca'
      path: '/manual-marca'
      fullPath: '/manual-marca'
      preLoaderRoute: typeof ManualMarcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/individual-familiar': {
      id: '/individual-familiar'
      path: '/individual-familiar'
      fullPath: '/individual-familiar'
      preLoaderRoute: typeof IndividualFamiliarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignSystemRoute: DesignSystemRoute,
  IndividualFamiliarRoute: IndividualFamiliarRoute,
  ManualMarcaRoute: ManualMarcaRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  StartRoute: StartRoute,
  TelemedicinaEmpresarialRoute: TelemedicinaEmpresarialRoute,
  TermosRoute: TermosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
